<script type="text/javascript">

//handle the formatting of the date
jQuery(document).ready(function(){	

	var runDate = jQuery('#runDate').val();
		var runTime = jQuery('#runTime').val();
		var runTimeAMPM = jQuery('#runTimeAMPM').val();
		var completeRunDateTime = "";
		if(runDate != "")
		{
			var runDateArray = runDate.split("/");
			if(runDateArray[0].length==1)
			{
				runDateArray[0]="0"+runDateArray[0];
			}
			var runingDate = runDateArray[2] + "-" + runDateArray[0] + "-" + runDateArray[1];		
			if(runTime != "")
			{
				var runTimeArray = runTime.split(":");
				if(runTimeArray[0] == "12")
				{
					runTimeArray[0] = "00";
					runTime = runTimeArray[0] + ":" + runTimeArray[1]
				}
				if(runTimeAMPM=="PM")
				{
					var runTimeArray2 = runTime.split(":");
					runTimeArray2[0] = parseInt(runTimeArray2[0]) + 12;
					runTime = runTimeArray2[0] + ":" + runTimeArray2[1];
				}
				runTime= runTime + ":00.000";
			}
			else
			{
				runTime="00:00:00.000";
			}			
			completeRunDateTime = runingDate + " " + runTime;
		jQuery("#SERVICE_TIME").val(completeRunDateTime);
		}	
//alert(completeRunDateTime);

	jQuery('.dateRun').change(function() {
		var runDate = jQuery('#runDate').val();
		var runTime = jQuery('#runTime').val();
		var runTimeAMPM = jQuery('#runTimeAMPM').val();
		var completeRunDateTime = "";
		if(runDate != "")
		{
			var runDateArray = runDate.split("/");
			if(runDateArray[0].length==1)
			{
				runDateArray[0]="0"+runDateArray[0];
			}
			var runingDate = runDateArray[2] + "-" + runDateArray[0] + "-" + runDateArray[1];		
			if(runTime != "")
			{
				var runTimeArray = runTime.split(":");
				if(runTimeArray[0] == "12")
				{
					runTimeArray[0] = "00";
					runTime = runTimeArray[0] + ":" + runTimeArray[1]
				}
				if(runTimeAMPM=="PM")
				{
					var runTimeArray2 = runTime.split(":");
					runTimeArray2[0] = parseInt(runTimeArray2[0]) + 12;
					runTime = runTimeArray2[0] + ":" + runTimeArray2[1];
				}
				runTime= runTime + ":00.000";
			}
			else
			{
				runTime="00:00:00.000";
			}			
			completeRunDateTime = runingDate + " " + runTime;
		jQuery("#SERVICE_TIME").val(completeRunDateTime);
	  //alert(completeRunDateTime);
		}	
	});
});
   
function datePicker(triger){
   jQuery(triger).datepicker({
       showOn: 'button',
       buttonImage: '<@ofbizContentUrl>/images/cal.gif</@ofbizContentUrl>',
       buttonImageOnly: false,
       <#if FORMAT_DATE?exists && FORMAT_DATE?has_content>
         <#assign format = "mm/dd/yy" />
       <#else>
         <#assign format = "mm/dd/yy" />
       </#if>
       dateFormat: '${format}'
   });
 }

</script>
<#if mode?has_content>
  		<#assign AMPM = "AM,PM"/>
      	<#assign AMPM = AMPM?split(",")/>
      	<!-- hidden fields for dates generated by JQuery -->
      	<input type="hidden" id="SERVICE_TIME" name="SERVICE_TIME" value="${parameters.SERVICE_TIME!""}"/>
		<!-- other hidden fields -->
		<input type="hidden" id="POOL_NAME" name="POOL_NAME" value="pool"/>
		<input type="hidden" name="productStoreId" value="${globalContext.productStoreId!""}" />
		<input type="hidden" name="browseRootProductCategoryId" value="${globalContext.rootProductCategoryId!""}" />
		<input type="hidden" name="emailCount" value="${globalContext.EMAIL_ABANDON_NUM!""}" />
		<input type="hidden" name="intervalHours" value="${globalContext.EMAIL_ABANDON_HRS!""}" />

	<#if schedJob?exists && schedJob?has_content>
		<#assign jobName = schedJob.jobName!"" />
	</#if>

<#if mode != "add">		
  <div class="infoRow">
    <div class="infoEntry">
      <div class="infoCaption">
        <label>${uiLabelMap.JobIdCaption}</label>
      </div>
      <div class="infoValue">
        	${parameters.jobId!jobId!""}
         	<input name="jobId" type="hidden" id="jobId" maxlength="20" value="${parameters.jobId!jobId!""}"/>
      </div>
    </div>
  </div>
</#if>  
  <div class="infoRow">
    <div class="infoEntry">
      <div class="infoCaption">
        <label>${uiLabelMap.JobNameCaption}</label>
      </div>
      <div class="infoValue">
        <#if mode=="add">
        	<input name="JOB_NAME" type="text" id="JOB_NAME" maxlength="20" value="${parameters.JOB_NAME!JOB_NAME!""}"/>
        <#else>
          	<input name="JOB_NAME" type="text" id="JOB_NAME" maxlength="20" value="${schedJob.jobName!jobName!""}"/>
        </#if>
      </div>
    </div>
  </div>
  
  <div class="infoRow">
    <div class="infoEntry">
      <div class="infoCaption">
        <label>${uiLabelMap.ServiceNameCaption}</label>
      </div>
      <div class="infoValue">
        <#if mode=="add">
        	<input name="SERVICE_NAME" type="text" id="SERVICE_NAME" maxlength="20" value="${parameters.SERVICE_NAME!SERVICE_NAME!""}"/>
        <#else>
          	<input name="SERVICE_NAME" type="text" id="SERVICE_NAME" maxlength="20" value="${schedJob.serviceName!serviceName!""}"/>
        </#if>
      </div>
    </div>
  </div>
  
  <div class="infoRow">
    <div class="infoEntry">
      <div class="infoCaption">
        <label>${uiLabelMap.StatusIdCaption}</label>
      </div>
      <div class="infoValue">
        <#if mode=="add">
        	PENDING
        	<input name="statusId" type="hidden" id="statusId" maxlength="20" value="PENDING"/>	
        <#else>
        	<#assign statusId = schedJob.statusId?split("_") />
            <#assign statusId = statusId[1] />
        	${statusId!""}
         	<input name="statusId" type="hidden" id="statusId" maxlength="20" value="${schedJob.statusId!statusId!""}"/>
        </#if>
      </div>
    </div>
  </div>
	
  <div class="infoRow">
    <div class="infoEntry ">
      <div class="infoCaption">
        <label>${uiLabelMap.RunDateTimeCaption}</label>
      </div>
      <div class="infoValue ">
        <div class="entryInput ">
        	<#if mode="add"> 
        		<input class="dateEntry dateRun" type="text" id="runDate" name="runDate" maxlength="40" value="${parameters.runDate!""}"/>
        	<#else>
        		<#if schedJob.runTime?exists && schedJob.runTime?has_content>
			        <#assign runDateTime = schedJob.runTime?string.short />
			        <#assign runDateTime = runDateTime?split(" ") />
			        <#assign runYear = schedJob.runTime?string("yyyy-MM-dd HH:mm:ss zzzz")?split("-") />
			        <#assign runYear = runYear[0] />
			        <#assign runDate = runDateTime[0] />
			        <#assign runDate = runDate?split("/") />
			        <#assign runDate = runDate[0] + "/" + runDate[1] + "/" + runYear />
			        <#assign runTime = runDateTime[1] />
			        <#assign runTimeAMPM = runDateTime[2] />
			    </#if>
	        	<#if schedJob.statusId == "SERVICE_PENDING">
	        		<input class="dateEntry dateRun" type="text" id="runDate" name="runDate" maxlength="40" value="${runDate!""}"/>
	        	<#else>
		        	${runDate!""}
		         	<input name="runDate" type="hidden" id="runDate" maxlength="20" value="${runDate!""}"/>
		        </#if>	
		    </#if>           
        </div>
      </div>

      <div>
        <label>${uiLabelMap.TimeCaption}</label>
      </div>
      <div class="infoValue">
        <div class="entryInput"> 
        	<#if mode="add"> 
        		<#assign selectedAMPM = parameters.runTimeAMPM!""/>
        		<input class="textEntry dateRun" type="text" id="runTime" name="runTime" maxlength="40" value="${parameters.runTime!runTime!""}"/>
				<select name="runTimeAMPM" id="runTimeAMPM" class="dateRun">
			              <#list AMPM as pm_am>
							      <option value='${pm_am!}' <#if selectedAMPM == pm_am >selected=selected</#if>>${pm_am?default(pm_am!)}</option>
						  </#list>  
			    </select>
        	<#else>
	        	<#if schedJob.statusId == "SERVICE_PENDING">
	        		<#assign selectedAMPM = runTimeAMPM!""/>
	        		<input class="textEntry dateRun" type="text" id="runTime" name="runTime" maxlength="40" value="${parameters.runTime!runTime!""}"/>
            		<select name="runTimeAMPM" id="runTimeAMPM" class="dateRun" >
			              <#list AMPM as pm_am>
				              <option value='${pm_am!}' <#if selectedAMPM == pm_am >selected=selected</#if>>${pm_am?default(pm_am!)}</option>
				          </#list> 
			        </select>
	        	<#else>
		        	${runTime!""} ${runTimeAMPM!""}
		         	<input class="textEntry" type="hidden" id="runTime" name="runTime" maxlength="40" value="${runTime!""}"/>
            		<input class="textEntry" type="hidden" id="runTimeAMPM" name="runTimeAMPM" maxlength="40" value="${runTimeAMPM!""}"/>
		        </#if>	
		    </#if>               
        </div>
      </div>
    </div>
  </div>

  <div class="infoRow">
    <div class="infoEntry ">
      <div class="infoCaption">
        <label>${uiLabelMap.StartDateTimeCaption}</label>
      </div>
      <div class="infoValue ">
        <div class="entryInput ">
        		<#if mode!="add">
		        	<#if schedJob.startDateTime?exists && schedJob.startDateTime?has_content>
				        <#assign startDateTime = schedJob.startDateTime?string.short />
				        <#assign startDateTime = startDateTime?split(" ") />
				        <#assign startYear = schedJob.startDateTime?string("yyyy-MM-dd HH:mm:ss zzzz")?split("-") />
				        <#assign startYear = startYear[0] />
				        <#assign startDate = startDateTime[0] />
				        <#assign startDate = startDate?split("/") />
				        <#assign startDate = startDate[0] + "/" + startDate[1] + "/" + startYear />
				        <#assign startTime = startDateTime[1] />
				        <#assign startTimeAMPM = startDateTime[2] />
			        </#if>
			        	${startDate!""}
			         	<input name="startDate" type="hidden" id="startDate" maxlength="20" value="${startDate!""}"/>
		        </#if>
        </div>
      </div>

      <div>
        <label>${uiLabelMap.TimeCaption}</label>
      </div>
      <div class="infoValue">
        <div class="entryInput"> 
	        	<#if mode!="add">
		        	${schedJob.startTime!startTime!""} ${schedJob.startTimeAMPM!startTimeAMPM!""}
		         	<input class="textEntry" type="hidden" id="startTime" name="startTime" maxlength="40" value="${schedJob.startTime!startTime!""}"/>
            		<input class="textEntry" type="hidden" id="startTimeAMPM" name="startTimeAMPM" maxlength="40" value="${schedJob.startTimeAMPM!startTimeAMPM!""}"/>
		        </#if>
        </div>
      </div>
    </div>
  </div>
  
 <#if mode!="add">
  <div class="infoRow">
    <div class="infoEntry ">
      <div class="infoCaption">
        <label>${uiLabelMap.FinishDateTimeCaption}</label>
      </div>
      <div class="infoValue ">
        <div class="entryInput ">
	        	<#if schedJob.finishDateTime?exists && schedJob.finishDateTime?has_content> 
		        	<#assign finishDateTime = schedJob.finishDateTime?string.short />
			        <#assign finishDateTime = finishDateTime?split(" ") />
			        <#assign finishYear = schedJob.finishDateTime?string("yyyy-MM-dd HH:mm:ss zzzz")?split("-") />
			        <#assign finishYear = finishYear[0] />
			        <#assign finishDate = finishDateTime[0] />
			        <#assign finishDate = finishDate?split("/") />
			        <#assign finishDate = finishDate[0] + "/" + finishDate[1] + "/" + finishYear />
			        <#assign finishTime = finishDateTime[1] />
			        <#assign finishTimeAMPM = finishDateTime[2] />
			    </#if>
		        	${schedJob.finishDate!finishDate!""}
		         	<input name="finishDate" type="hidden" id="finishDate" maxlength="20" value="${schedJob.finishDate!finishDate!""}"/>
        </div>
      </div>

      <div>
        <label>${uiLabelMap.TimeCaption}</label>
      </div>
      <div class="infoValue">
        <div class="entryInput"> 
		        	${schedJob.finishTime!finishTime!""} ${schedJob.finishTimeAMPM!finishTimeAMPM!""}
		         	<input class="textEntry" type="hidden" id="finishTime" name="finishTime" maxlength="40" value="${schedJob.finishTime!finishTime!""}"/>
            		<input class="textEntry" type="hidden" id="finishTimeAMPM" name="finishTimeAMPM" maxlength="40" value="${schedJob.finishTimeAMPM!finishTimeAMPM!""}"/>
		         
        </div>
      </div>
    </div>
  </div>
 </#if> 
 
 <#if mode!="add"> 
  <div class="infoRow">
    <div class="infoEntry ">
      <div class="infoCaption">
        <label>${uiLabelMap.CancelDateTimeCaption}</label>
      </div>
      <div class="infoValue ">
        <div class="entryInput ">
	        	<#if schedJob.cancelDateTime?exists && schedJob.cancelDateTime?has_content> 
		        	<#assign cancelDateTime = schedJob.cancelDateTime?string.short />
			        <#assign cancelDateTime = cancelDateTime?split(" ") />
			        <#assign cancelYear = schedJob.cancelDateTime?string("yyyy-MM-dd HH:mm:ss zzzz")?split("-") />
			        <#assign cancelYear = cancelYear[0] />
			        <#assign cancelDate = cancelDateTime[0] />
			        <#assign cancelDate = cancelDate?split("/") />
			        <#assign cancelDate = cancelDate[0] + "/" + cancelDate[1] + "/" + cancelYear />
			        <#assign cancelTime = cancelDateTime[1] />
			        <#assign cancelTimeAMPM = cancelDateTime[2] />
			    </#if>
		        	${schedJob.cancelDate!cancelDate!""}
		         	<input name="cancelDate" type="hidden" id="cancelDate" maxlength="20" value="${schedJob.cancelDate!cancelDate!""}"/> 
        </div>
      </div>

      <div>
        <label>${uiLabelMap.TimeCaption}</label>
      </div>
      <div class="infoValue">
        <div class="entryInput">   
		        	${schedJob.cancelTime!cancelTime!""} ${schedJob.cancelTimeAMPM!cancelTimeAMPM!""}
		         	<input class="textEntry" type="hidden" id="cancelTime" name="cancelTime" maxlength="40" value="${schedJob.cancelTime!cancelTime!""}"/>
            		<input class="textEntry" type="hidden" id="cancelTimeAMPM" name="cancelTimeAMPM" maxlength="40" value="${schedJob.cancelTimeAMPM!cancelTimeAMPM!""}"/>           
        </div>
      </div>
    </div>
  </div>
 </#if> 
  
  
<#else>
    ${uiLabelMap.NoDataAvailableInfo}
</#if>
